targets = [
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "i686-pc-windows-msvc" },
    { triple = "i686-unknown-linux-gnu" },
    { triple = "aarch64-apple-darwin" },
]

[bans]
multiple-versions = "allow"
allow-build-scripts = [
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
]
